#!/bin/sh
#
# Christian Gaser - christian.gaser@uni-jena.de
# Department of Psychiatry
# University of Jena
#
# Copyright Christian Gaser, University of Jena.
# $Id: CAT_DumpCurv_ui 85 2009-01-14 23:29:48Z gaser $
#

########################################################
# global parameters
########################################################

use_absolute=1
method=0
fwhm=0

########################################################
# run main
########################################################

main ()
{
	check_tools
  parse_args ${1+"$@"}
  DumpCurv

  exit 0
}


########################################################
# DumpCurv
########################################################
DumpCurv ()
{
  case "$method" in
    0)
        str='mc'
        ;;
    1)
        str='gc'
        ;;
    2)
        str='cv'
        ;;
    3)
        str='si'
        ;;
    4)
        str='mc0'
        ;;
  esac
  if [ "$use_absolute" == 1 ]; then
    str=a$str
  fi

  if [ ! "$fwhm" == 0 ]; then
    str=${fwhm}mm_${str}
  fi

  if [ -n "$ARGV_list" ]
  then
		for subject in $ARGV_list
		do
		  outputname=${SUBJECTS_DIR}/${subject}/surf/
		  if [ ! -d "$outputname" ]; then
	  		echo Directory $outputname not found.
	  		exit 1
	  	fi
    	echo calculating ${SUBJECTS_DIR}/${subject} 
    	tmp_name=/tmp/$$_avg
    	for hemi in lh rh; do
    		for name in ${outputname}${hemi}.white ${outputname}${hemi}.pial; do
				  if [ ! -f "$name" ]; then
			  		echo File $name not found.
	  				exit 1
	  			fi
	  		done
	    	CAT_AverageSurfaces -avg $tmp_name ${outputname}${hemi}.white ${outputname}${hemi}.pial >/dev/null 2>&1
			  if [ ! -f "$tmp_name" ]; then
		  		echo File $tmp_name not found. Error using CAT_AverageSurfaces.
  				exit 1
  			fi
  	  	CAT_DumpCurv $tmp_name ${outputname}${hemi}.${str}_central $method $fwhm $use_absolute
  	  	rm $tmp_name
  		done
  	done
  else
		echo "No arguments given."
		echo
		usage
		echo "Use the --help option for more information."
		exit 1
  fi

}


########################################################
# check arguments and files
########################################################

parse_args ()
{
  local optname optarg

  while [ $# -gt 0 ]
  do
	optname="`echo $1 | sed 's,=.*,,'`"
	optarg="`echo $1 | sed 's,^[^=]*=,,'`"
	case "$1" in
		--a* | -a*)
			use_absolute=1
			;;
		--f* | -f*)
			optarg=`echo $optarg | sed 's,[^0-9],,g'`
			exit_if_empty "$optname" "$optarg"
			fwhm=$optarg
			;;
		--mc | -mc)
			method=0
			;;
		--g* | -g*)
			method=1
			;;
		--c* | -c*)
			method=2
			;;
		--s* | -s*)
			method=3
			;;
		--mc0 | -mc0)
			method=4
			;;
		-h | --help | -v | --version | -V)
			help
			exit 1
			;;
		-*)
			echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
			;;
		*)
			ARGV_list="$ARGV_list $1"
			;;
	esac
    shift
  done

}


########################################################
# check arguments
########################################################

exit_if_empty ()
{
  local desc val

  desc="$1"
  shift
  val="$*"

  if [ -z "$val" ]
  then
	echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
	exit 1
  fi
}

########################################################
# check if CAT tools exist
########################################################

check_tools ()
{
	for name in CAT_DumpCurv CAT_AverageSurfaces; do
	  found=`which ${name}`
  	if [ ! -n "$found" ];then
    	echo $name not found.
    	exit 1
  	fi
  done
}

########################################################
# usage
########################################################
usage ()
{
cat <<__EOM__
USAGE: CAT_DumpCurvL4FS subject [subject2 .. subjectN] [-mc|-mc0|-gc|-cv|-si] [-a]
        [-f=fwhm_in_mm]
		
__EOM__
}

########################################################
# help
########################################################

help ()
{
cat <<__EOM__

PURPOSE:
Compute curvature-based parameters from a central surface. The result is a file
containing the values for each node. The values can be optionally filtered using a
diffusion heat kernel and values can be saved as absolute values.
The central surface is otbained by averaging the white and pial surface.

USAGE:
    CAT_DumpCurvL4FS subject [subject2 .. subjectN] [-mc|-mc0|-gc|-cv|-si] [-a]
        [-f=fwhm_in_mm]
    
OPTIONS:
	subject    - a subject directory in the SUBJECTS_DIR path
	-f         - diffusion heat kernel smoothing defined in fwhm in mm
	-a         - calculate absolute values of parameters [default]
	-mc        - calculate mean curvature averaged over 3mm [default]                
	-mc0       - calculate mean curvature                
	-gc        - calculate gaussian curvature                
	-cv        - calculate curvedness                
	-si        - calculate shape index                
    
EXAMPLE:
    CAT_DumpCurvL4FS bert fsaverage -mc -a 
    This will calculate absolute mean curvature. The output files will be named 
    SUBJECTS_DIR/subject/surf/[lr]h.amc_central.

INPUT:
    Freesurfer or MNI-OBJ surface files

OUTPUT:
    Values-files

USED FUNCTIONS:
    CAT_DumpCurv
    CAT_AverageSurfaces

This script was written by Christian Gaser (christian.gaser@uni-jena.de).

__EOM__
}

########################################################
# call main program
########################################################

main ${1+"$@"}
