#!/bin/sh
#
# Christian Gaser - christian.gaser@uni-jena.de
# Department of Psychiatry
# University of Jena
#
# Copyright Christian Gaser, University of Jena.
# $Id: CAT_DumpCurv_ui 85 2009-01-14 23:29:48Z gaser $
#

########################################################
# global parameters
########################################################

use_absolute=0
method=0
fwhm=0

########################################################
# run main
########################################################

main ()
{
  parse_args ${1+"$@"}
  DumpCurv

  exit 0
}


########################################################
# DumpCurv
########################################################
DumpCurv ()
{
  case "$method" in
    0)
        str='mc'
        ;;
    1)
        str='gc'
        ;;
    2)
        str='cv'
        ;;
    3)
        str='si'
        ;;
    4)
        str='mc0'
        ;;
  esac
  if [ "$use_absolute" == 1 ]; then
    str=a$str
  fi

  if [ -n "$ARGV_list" ]
  then
    get_basename $ARGV_list
    echo calculating $outputname
    echo CAT_DumpCurv ${outputname}.white ${outputname}.${str} $method $fwhm $use_absolute
  else
	echo "No arguments given."
	echo
	usage
	echo "Use the --help option for more information."
	exit 1
  fi

}

########################################################
# get_basename
########################################################

get_basename ()
{
  outputname=${SUBJECTS_DIR}/${1}/surf/${2}
}

########################################################
# check arguments and files
########################################################

parse_args ()
{
  local optname optarg

  while [ $# -gt 0 ]
  do
	optname="`echo $1 | sed 's,=.*,,'`"
	optarg="`echo $1 | sed 's,^[^=]*=,,'`"
	case "$1" in
		--a* | -a*)
			use_absolute=1
			;;
		--mc | -mc)
			method=0
			;;
		--g* | -g*)
			method=1
			;;
		--c* | -c*)
			method=2
			;;
		--s* | -s*)
			method=3
			;;
		--mc0 | -mc0)
			method=4
			;;
		-h | --help | -v | --version | -V)
			help
			exit 1
			;;
		-*)
			echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
			;;
		*)
			ARGV_list="$ARGV_list $1"
			;;
	esac
    shift
  done

}


########################################################
# check arguments
########################################################

exit_if_empty ()
{
  local desc val

  desc="$1"
  shift
  val="$*"

  if [ -z "$val" ]
  then
	echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
	exit 1
  fi
}

########################################################
# usage
########################################################
usage ()
{
cat <<__EOM__
USAGE: DumpCurv_ui subject hemisphere [-mc|-mc0|-gc|-cv|-si] [-a]
		
__EOM__
}

########################################################
# help
########################################################

help ()
{
cat <<__EOM__

PURPOSE:
Compute curvature-based parameters from a given freesurfer file. The result is a file
containing the values for each node. The values can be optionally saved as absolute values.

USAGE:
    CAT_DumpCurvL4FS_ui subject hemisphere [-mc|-mc0|-gc|-cv|-si] [-a]
    
OPTIONS:
	subject    - a subject directory in the SUBJECTS_DIR path
	hemisphere - lh or rh
	-a         - calculate absolute values of parameters
	-mc        - calculate mean curvature averaged over 3mm [default]                
	-mc0       - calculate mean curvature                
	-gc        - calculate gaussian curvature                
	-cv        - calculate curvedness                
	-si        - calculate shape index                
    
EXAMPLE:
    CAT_DumpCurvL4FS_ui bert lh -mc -a 
    This will calculate absolute mean curvature. The output files will be named according 
    to the inputname with a prepended amc_.

INPUT:
    Freesurfer of MNI surface files

OUTPUT:
    Values-files

USED FUNCTIONS:
    CAT_DumpCurv

This script was written by Christian Gaser (christian.gaser@uni-jena.de).

__EOM__
}

########################################################
# call main program
########################################################

main ${1+"$@"}
