#!/bin/sh

tmp_poly=/tmp/poly$$

name=`echo $1|sed -e 's/.obj/_FD1.txt/'`
name=FD.txt

# start with lower resolution
subdivide_polygons $1 $tmp_poly 2560
#cp $1 $tmp_poly
n_polygons=`print_n_polygons $tmp_poly`
n_polygons0=$n_polygons

n=1
area=`CAT_DumpSurfArea ${tmp_poly}.obj NULL log| sed -e 's/Total log. surface area: //g'`

echo $n $area > $name
echo $n $n_polygons $area

while [ $n_polygons -gt 16 ];
do
	n_polygons=`expr $n_polygons / 2`
	n=`expr $n \* 2`
	subdivide_polygons ${tmp_poly}.obj ${tmp_poly}_sub.obj $n_polygons
	subdivide_polygons ${tmp_poly}_sub.obj ${tmp_poly}_${n}.obj $n_polygons0
	CAT_DumpSurfArea ${tmp_poly}_${n}.obj ${tmp_poly}_${n}.txt log
	area=`CAT_DumpSurfArea ${tmp_poly}_sub.obj NULL log|sed -e 's/Total log. surface area: //'`
	echo $n $area >> $name
	echo $n $n_polygons $area
done

#rm ${tmp_poly}*
