#!/bin/sh
#
# Christian Gaser - christian.gaser@uni-jena.de
# Department of Psychiatry
# University of Jena
#
# Copyright Christian Gaser, University of Jena.
# $Id$
#

########################################################
# global parameters
########################################################

use_absolute=0
method=0
fwhm=0
removestr=''
noclobber=0
gifti=0

########################################################
# run main
########################################################

main ()
{
  parse_args ${1+"$@"}
  DumpCurv

  exit 0
}


########################################################
# DumpCurv
########################################################
DumpCurv ()
{
  if [ -n "$ARGV_list" ]
  then
  for i in $ARGV_list
  do
     get_outputname $i
     if [ -f "${outputname}" ] && [ "$noclobber" == 1 ]; then
        echo $outputname will be not overwritten. Do not use -noclobber if you want to overwrite file.
     else
       echo calculating $outputname
       CAT_DumpCurv $i $outputname $method $fwhm $use_absolute
     fi
  done
  else
  echo "No arguments given."
  echo
  usage
  echo "Use the --help option for more information."
  exit 1
  fi

}

########################################################
# get_outputname
########################################################

get_outputname ()
{
  bn=`basename $1|sed -e s,.obj,,g -e s,.gii,,g -e s,${removestr},,g`
  dn=`dirname $1`
  case "$method" in
    0)
        str='mc'
        ;;
    1)
        str='gc'
        ;;
    2)
        str='cv'
        ;;
    3)
        str='si'
        ;;
    4)
        str='mc0'
        ;;
    5)
        str='sd'
        ;;
  esac
  if [ "$use_absolute" == 1 ]; then
    str=a$str
  fi
  if [ ! "$fwhm" == 0 ]; then
    str=${fwhm}mm_${str}
  fi
  
  # check whether we have freesurfer files
  # and use different output name
  bn1=`echo $bn | cut -f1 -d'.'`
  if [ "$bn1" == "lh" ] || [ "$bn1" == "rh" ]; then
    bn=`basename $1|sed -e s,.obj,,g -e s,.gii,,g -e s,h.central,h,g -e s,${removestr},,g -e s,lh.,,g -e s,rh.,,g`
    outputname=${dn}/${bn1}.${str}.${bn}
  else if [ "$gifti" == 1 ]; then
    outputname=${dn}/${str}_${bn}.gii
  else
    outputname=${dn}/${str}_${bn}.txt
  fi
  fi
}

########################################################
# check arguments and files
########################################################

parse_args ()
{
  local optname optarg

  while [ $# -gt 0 ]
  do
  optname="`echo $1 | sed 's,=.*,,'`"
  optarg="`echo $1 | sed 's,^[^=]*=,,'`"
  case "$1" in
    --a* | -a*)
      use_absolute=1
      ;;
    --r* | -r*)
      exit_if_empty "$optname" "$optarg"
      removestr=$optarg
      ;;
    --f* | -f*)
      optarg=`echo $optarg | sed 's,[^0-9],,g'`
      exit_if_empty "$optname" "$optarg"
      fwhm=$optarg
      ;;
    --n* | -n*)
      noclobber=1
      ;;
    --gifti | -gifti)
      gifti=1
      ;;
    --mc | -mc)
      method=0
      ;;
    --gc* | -gc*)
      method=1
      ;;
    --c* | -c*)
      method=2
      ;;
    --si | -si)
      method=3
      ;;
    --mc0 | -mc0)
      method=4
      ;;
    --sd | -sd)
      method=5
      ;;
    -h | --help | -v | --version | -V)
      help
      exit 1
      ;;
    -*)
      echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
      ;;
    *)
      ARGV_list="$ARGV_list $1"
      ;;
  esac
    shift
  done

}


########################################################
# check arguments
########################################################

exit_if_empty ()
{
  local desc val

  desc="$1"
  shift
  val="$*"

  if [ -z "$val" ]
  then
  echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
  exit 1
  fi
}

########################################################
# usage
########################################################
usage ()
{
cat <<__EOM__
USAGE: CAT_DumpCurv_ui name [name2 name3 ... nameN] [-noclobber] [-mc|-mc0|-gc|-cv|-si|-sd] [-a]
        [-f=fwhm_in_mm] [-r=remove_str_from_outputname] [-gifti]
    
__EOM__
}

########################################################
# help
########################################################

help ()
{
cat <<__EOM__

PURPOSE:
Compute curvature-based parameters from a given obj-file. The result is a txt-file
containing the values for each node. The values can be optionally filtered using a
diffusion heat kernel and values can be saved as absolute values.

USAGE:
    CAT_DumpCurv_ui name.obj [name2.obj ... nameN.obj] [-mc|-mc0|-gc|-cv|-si|-sd] [-a]
        [-noclobber] [-f=fwhm_in_mm] [-r=remove_str_from_outputname] [-gifti]
    
OPTIONS:
  name.obj   - input obj-file(s)
  -f         - diffusion heat kernel smoothing defined in fwhm in mm
  -a         - calculate absolute values of parameters
  -r         - remove string from outputname
  -mc        - calculate mean curvature averaged over 3mm [default]                
  -mc0       - calculate mean curvature                
  -gc        - calculate gaussian curvature                
  -cv        - calculate curvedness                
  -si        - calculate shape index                
  -sd        - calculate sulcal depth like estimator                
  -gifti     - save output as gifti file
  -noclobber - do not overwrite existing file
    
EXAMPLE:
    CAT_DumpCurv_ui *.obj -mc -a -f=10 -r=cerebrum_a305_12p
    This will calculate absolute mean curvature smoothed with fwhm of 10mm. The outputfiles
    will be named according to the inputname and the string "cerebrum_a305_12p" will removed.
    If the name of the input is ab01_cerebrum_a305_12p.obj the outputname will be called
    10mm_amc_ab01.txt.

INPUT:
    MNI obj-files

OUTPUT:
    txt-files where the string defined using the option "-r" is removed. The names will be
    prepended by a string indicating the filtersize and the used method.

USED FUNCTIONS:
    CAT_DumpCurv

This script was written by Christian Gaser (christian.gaser@uni-jena.de).

__EOM__
}

########################################################
# call main program
########################################################

main ${1+"$@"}
