#!/bin/sh
#
# Christian Gaser - christian.gaser@uni-jena.de
# Department of Psychiatry
# University of Jena
#
# Copyright Christian Gaser, University of Jena.
# $Id$
#

########################################################
# global parameters
########################################################

hemi="lh rh"
ascii=0
noclobber=0
gifti=0

########################################################
# run main
########################################################

main ()
{
  check_tools
  parse_args ${1+"$@"}
  process

  exit 0
}


########################################################
# DumpCurv
########################################################
process ()
{

  if [ -n "$ARGV_list" ]
  then
    for subject in $ARGV_list
    do

      surfdir=${subject}/surf
      if [ ! -d "$surfdir" ]; then
        echo Directory $surfdir not found.
        break
      fi

      subject_name=`basename $subject`
      tmp_name=/tmp/$$_central
      
      for i in $hemi; do
        for name in ${surfdir}/${i}.pial ${surfdir}/${i}.white ${surfdir}/${i}.sphere; do
          if [ ! -f "$name" ]; then
            echo File $name not found.
            break
          fi
        done
        
        name=${surfdir}/${i}.fd
        if [ "$gifti" == 1 ]; then
          name=${name}.gii
        else if [ "$ascii" == 1 ]; then
          name=${name}.txt
        fi
        fi

        if [ -f "${name}" ] && [ "$noclobber" == 1 ]; then
          echo $name will be not overwritten. Do not use -noclobber if you want to overwrite file.
        else
          echo save local FD in $name
          CAT_AverageSurfaces -avg ${tmp_name}_${i} ${surfdir}/${i}.pial ${surfdir}/${i}.white >/dev/null 2>&1
          CAT_FractalDimension -sphere ${surfdir}/${i}.sphere -nosmooth ${tmp_name}_${i} ${surfdir}/${i}.sphere $name
          if [ -f ${tmp_name}_${i} ]; then rm ${tmp_name}_${i}; fi
        fi
      done
    done
  else
    echo "No arguments given."
    echo
    usage
    echo "Use the --help option for more information."
    exit 1
  fi

}


########################################################
# check arguments and files
########################################################

parse_args ()
{
  local optname optarg

  while [ $# -gt 0 ]
  do
  optname="`echo $1 | sed 's,=.*,,'`"
  optarg="`echo $1 | sed 's,^[^=]*=,,'`"
  case "$1" in
    --f* | -f*)
      optarg=`echo $optarg | sed 's,[^0-9],,g'`
      exit_if_empty "$optname" "$optarg"
      fwhm=$optarg
      ;;
    --a* | -a*)
      ascii=1
      ;;
    --g* | -g*)
      gifti=1
      ascii=0
      ;;
    --n* | -n*)
      noclobber=1
      ;;
    --lh* | -lh*)
      hemi=lh
      ;;
    --rh* | -rh*)
      hemi=rh
      ;;
    -h | --help | -v | --version | -V)
      help
      exit 1
      ;;
    -*)
      echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
      ;;
    *)
      ARGV_list="$ARGV_list $1"
      ;;
  esac
    shift
  done

}


########################################################
# check arguments
########################################################

exit_if_empty ()
{
  local desc val

  desc="$1"
  shift
  val="$*"

  if [ -z "$val" ]
  then
  echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
  exit 1
  fi
}

########################################################
# check if CAT tools exist
########################################################

check_tools ()
{
  for name in CAT_FractalDimension CAT_AverageSurfaces; do
    found=`which ${name}`
    if [ ! -n "$found" ];then
      echo $name not found.
      exit 1
    fi
  done
}

########################################################
# usage
########################################################
usage ()
{
cat <<__EOM__
USAGE: CAT_FractalDimensionFS_ui subject [subject2 .. subjectN] [-a] [-noclobber] [-lh|-rh] [-gifti]
    
__EOM__
}

########################################################
# help
########################################################

help ()
{
cat <<__EOM__

PURPOSE:
Calculate fractal dimension (FD) of central surface fo freesurfer surfaces. The output is unsmoothed 
and resampled back to the original surface.

USAGE:
        CAT_FractalDimensionFS_ui subject [subject2 .. subjectN] [-a] [-noclobber] [-lh|rh] [-gifti]                      
    
OPTIONS:
  subject    - one or more subject directories
  -a         - save output as ascii (text) file
  -lh        - resample left hemisphere only
  -rh        - resample right hemisphere only
  -gifti     - save output as gifti file
  -noclobber - do not overwrite existing file
    
EXAMPLE:
    CAT_FractalDimensionFS_ui ${SUBJECTS_DIR}/[a-d]*
    This will estimate FD values of all subject with a beginning a-d in the folder ${SUBJECTS_DIR}
    for both hemispheres.

INPUT:
    Freesurfer or MNI-OBJ surface files

OUTPUT:
    Values-files

USED FUNCTIONS:
    CAT_FractalDimension
    CAT_AverageSurfaces

This script was written by Christian Gaser (christian.gaser@uni-jena.de).

__EOM__
}

########################################################
# call main program
########################################################

main ${1+"$@"}
