#!/bin/sh
#
# Christian Gaser - christian.gaser@uni-jena.de
# Department of Psychiatry
# University of Jena
#
# Copyright Christian Gaser, University of Jena.
# $Id$
#

########################################################
# global parameters
########################################################

noclobber=0
gifti=0
DNAME=`dirname $0`
export PATH=$PATH:$DNAME

########################################################
# run main
########################################################

main ()
{
  check_tools
  parse_args ${1+"$@"}
  process

  exit 0
}


########################################################
# DumpCurv
########################################################
process ()
{

  if [ -n "$ARGV_list" ]
  then
    for surface in $ARGV_list
    do

      sphere=`echo $surface | sed 's,.central.,.sphere.,g'`      
      name=`echo $surface | sed 's,.central.,.fractaldimension.,g'`
            
      if [ ! -f "$sphere" ]; then
        echo File $sphere not found.
        exit
      fi
        
      if [ "$gifti" == 1 ]; then
        name=$name.gii
      fi

      if [ -f "$name" ] && [ "$noclobber" == 1 ]; then
        echo $name will be not overwritten. Do not use -noclobber if you want to overwrite file.
      else
        echo save local FD in $name
        CAT_FractalDimension -sphere $sphere -nosmooth $surface $sphere $name
      fi
    done
  else
    echo "No arguments given."
    echo
    usage
    echo "Use the --help option for more information."
    exit 1
  fi

}


########################################################
# check arguments and files
########################################################

parse_args ()
{
  local optname optarg

  while [ $# -gt 0 ]
  do
  optname="`echo $1 | sed 's,=.*,,'`"
  optarg="`echo $1 | sed 's,^[^=]*=,,'`"
  case "$1" in
    --gifti* | -g*)
      gifti=1
      ;;
    --n* | -n*)
      noclobber=1
      ;;
    -h | --help | -v | --version | -V)
      help
      exit 1
      ;;
    -*)
      echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
      ;;
    *)
      ARGV_list="$ARGV_list $1"
      ;;
  esac
    shift
  done

}


########################################################
# check arguments
########################################################

exit_if_empty ()
{
  local desc val

  desc="$1"
  shift
  val="$*"

  if [ -z "$val" ]
  then
  echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
  exit 1
  fi
}

########################################################
# check if CAT tools exist
########################################################

check_tools ()
{
  for name in CAT_FractalDimension; do
    found=`which ${name}`
    if [ ! -n "$found" ];then
      echo $name not found.
      exit 1
    fi
  done
}

########################################################
# usage
########################################################
usage ()
{
cat <<__EOM__
USAGE: CAT_FractalDimension_ui surface [surface2 .. surfaceN] [-noclobber] [-gifti]
    
__EOM__
}

########################################################
# help
########################################################

help ()
{
cat <<__EOM__

PURPOSE:
Calculate fractal dimension (FD) of central surfaces. The output is unsmoothed 
and resampled back to the original surface.

USAGE:
        CAT_FractalDimension_ui surface [surface2 .. surfaceN] [-noclobber] [-gifti]                      
    
OPTIONS:
  surface    - one or more central surfaces
  -gifti     - save output as gifti file
  -noclobber - do not overwrite existing file
    
EXAMPLE:
    CAT_FractalDimension_ui lh.central.*
    This will estimate FD values in the left hemisphere for all surface.

INPUT:
    Freesurfer or MNI-OBJ surface files

OUTPUT:
    Values-files

USED FUNCTIONS:
    CAT_FractalDimension

This script was written by Christian Gaser (christian.gaser@uni-jena.de).

__EOM__
}

########################################################
# call main program
########################################################

main ${1+"$@"}
