#!/bin/sh
#
# Christian Gaser - christian.gaser@uni-jena.de
# Department of Psychiatry
# University of Jena
#
# Copyright Christian Gaser, University of Jena.
# $Id$
#

########################################################
# global parameters
########################################################

fwhm=30
fwhm_surf=100
method=0
removestr=''
noclobber=0

########################################################
# run main
########################################################

main ()
{
  parse_args ${1+"$@"}
  DumpGI

  exit 0
}


########################################################
# DumpGI
########################################################
DumpGI ()
{
  if [ -n "$ARGV_list" ]
  then
  for i in $ARGV_list
  do
     get_outputname $i
     if [ -f "${outputname}" ] && [ "$noclobber" == 1 ]; then
       echo $outputname will be not overwritten. Do not use -noclobber if you want to overwrite file.
     else
       echo calculating $outputname
       CAT_DumpGI $i $outputname $fwhm $fwhm_surf $method
     fi
  done
  else
  echo "No arguments given."
  echo
  usage
  echo "Use the --help option for more information."
  exit 1
  fi

}

########################################################
# get_outputname
########################################################

get_outputname ()
{
  bn=`basename $1|sed -e s,.obj,,g -e s,${removestr},,g`
  dn=`dirname $1`
  case "$method" in
    0)
        str='gi_mc'
        ;;
    1)
        str='gi_gc'
        ;;
    2)
        str='gi_cv'
        ;;
    3)
        str='gi_si'
        ;;
    4)
        str='gi_mc0'
        ;;
  esac
  if [ ! "$fwhm" == 0 ]; then
    str=${fwhm}mm_${str}
  fi

  outputname=${dn}/${str}_${bn}.txt
}

########################################################
# check arguments and files
########################################################

parse_args ()
{
  local optname optarg

  while [ $# -gt 0 ]
  do
  optname="`echo $1 | sed 's,=.*,,'`"
  optarg="`echo $1 | sed 's,^[^=]*=,,'`"
  case "$1" in
    --r* | -r*)
      exit_if_empty "$optname" "$optarg"
      removestr=$optarg
      ;;
    --sf* | -sf*)
      optarg=`echo $optarg | sed 's,[^0-9],,g'`
      exit_if_empty "$optname" "$optarg"
      fwhm_surf=$optarg
      ;;
    --f* | -f*)
      optarg=`echo $optarg | sed 's,[^0-9],,g'`
      exit_if_empty "$optname" "$optarg"
      fwhm=$optarg
      ;;
    --n* | -n*)
      noclobber=1
      ;;
    --mc | -mc)
      method=0
      ;;
    --cv* | -cv*)
      method=2
      ;;
    --si* | -si*)
      method=3
      ;;
    --mc0 | -mc0)
      method=4
      ;;
    -h | --help | -v | --version | -V)
      help
      exit 1
      ;;
    -*)
      echo "`basename $0`: ERROR: Unrecognized option \"$1\"" >&2
      ;;
    *)
      ARGV_list="$ARGV_list $1"
      ;;
  esac
    shift
  done

}


########################################################
# check arguments
########################################################

exit_if_empty ()
{
  local desc val

  desc="$1"
  shift
  val="$*"

  if [ -z "$val" ]
  then
  echo "ERROR: No argument given with \"$desc\" command line argument!" >&2
  exit 1
  fi
}

########################################################
# usage
########################################################
usage ()
{
cat <<__EOM__
USAGE: DumpGI_ui name [name2 name3 ... nameN] [-noclobber]  [-mc|-mc0|-cv|-si]
        [-f=fwhm_in_mm] [-sf=surf_fwhm_in_mm] [-r=remove_str_from_ouputname]
    
__EOM__
}

########################################################
# help
########################################################

help ()
{
cat <<__EOM__

PURPOSE:
Calculate gyrification index (GI) using the ratio of local surface area and local inflated
surface area. Local surface area can be approximated by use of different methods.

USAGE:
    CAT_DumpGI_ui name.obj [name2.obj ... nameN.obj] [-noclobber] [-mc|-mc0|-cv|-si]
        [-f=fwhm_in_mm] [-sf=surf_fwhm_in_mm] [-r=remove_str_from_ouputname]
    
OPTIONS:
  name.obj   - input obj-file(s)
  -f         - diffusion heat kernel smoothing defined in fwhm in mm
  -sf        - diffusion heat kernel smoothing defined in fwhm in mm for surface inflating
  -r         - remove string from outputname
  -mc        - calculate mean curvature averaged over 3mm [default]                
  -mc0       - calculate mean curvature                
  -cv        - calculate curvedness                
  -si        - calculate shape index                
    -noclobber - do not overwrite existing file
    
EXAMPLE:
    CAT_DumpGI_ui *.obj -mc -a -f=30 -r=cerebrum_a305_12p
    This will calculate GI based on mean curvature smoothed with fwhm of 30mm. The outputfiles
    will be named according to the inputname and the string "cerebrum_a305_12p" will removed.
    If the name of the input is ab01_cerebrum_a305_12p.obj the outputname will be called
    30mm_gi_mc_ab01.txt.

INPUT:
    MNI obj-files

OUTPUT:
    txt-files where the string defined using the option "-r" is removed. The names will be
    prepended by a string indicating the filtersize and the used method.

USED FUNCTIONS:
    CAT_DumpGI

This script was written by Christian Gaser (christian.gaser@uni-jena.de).

__EOM__
}

########################################################
# call main program
########################################################

main ${1+"$@"}
