#!/bin/sh
# Christian Gaser - christian.gaser@uni-jena.de
# Department of Psychiatry
# University of Jena
#
# Copyright Christian Gaser, University of Jena.
# $Id$
#

if [ $# -lt 4 ]; then
	echo "Usage $0 WM.mnc WM.obj Wmout.obj [threshold] [curv] [max_search_distance]"
	exit
fi

if [ $# -eq 4 ]; then
    th=$4
else
    th=0.5
fi

if [ $# -eq 5 ]; then
    curv=$5
else
    curv=0.1
fi

if [ $# -eq 6 ]; then
    dist=$6
else
    dist=15
fi

# parameters for deforming WM
step="0.1 0.1 $dist 0 $th1 $th1 n 0 0 0"

iters=250
model="-1 0.1 avg -0.01 0.01"
CAT_DeformSurf $image none 0 0 0 $2 $3 none 0 1 $model $step $iters 0.01 0.0

iters=250
model="-1 .5 avg -$curv $curv"
CAT_DeformSurf $image none 0 0 0 $3 $3 none 0 1 $model $step $iters 0.01 0.0
