name: Build Binaries

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            arch: arm64
            artifact: cat-surface-macos-arm64
          - os: macos-13
            arch: x64
            artifact: cat-surface-macos-x86
          - os: ubuntu-22.04
            arch: x64
            artifact: cat-surface-ubuntu-x86_64
          - os: ubuntu-22.04
            arch: arm64
            artifact: cat-surface-ubuntu-arm64
          - os: windows-latest
            arch: x64
            artifact: cat-surface-windows-x86
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up MSYS2
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          install: autoconf automake libtool autoconf-archive make pkgconf gcc mingw-w64-x86_64-expat mingw-w64-x86_64-fftw zip

      - name: Install dependencies (Ubuntu x86_64)
        if: matrix.os == 'ubuntu-22.04' && matrix.arch == 'x64'
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool autoconf-archive build-essential pkg-config libfftw3-dev zip

      - name: Install dependencies (Ubuntu ARM64 cross-compile)
        if: matrix.os == 'ubuntu-22.04' && matrix.arch == 'arm64'
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake libtool autoconf-archive pkg-config zip \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            libfftw3-dev:arm64

      - name: Install dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: brew install autoconf automake libtool autoconf-archive fftw

      - name: Configure (non-Windows, x86_64)
        if: matrix.os != 'windows-latest' && matrix.arch != 'arm64'
        run: |
          autoupdate
          autoreconf -fi
          export CPPFLAGS="-I/opt/homebrew/include"
          export LDFLAGS="-L/opt/homebrew/lib"
          ./configure --enable-static --disable-shared --disable-doc

      - name: Configure (non-Windows, x86_64)
        if: matrix.os == 'macos-14' && matrix.arch == 'arm64'
        run: |
          autoupdate
          autoreconf -fi
          export CPPFLAGS="-I/opt/homebrew/include"
          export LDFLAGS="-L/opt/homebrew/lib"
          ./configure --enable-static --disable-shared --disable-doc

      - name: Configure (Ubuntu ARM64 cross-compile)
        if: matrix.os == 'ubuntu-22.04' && matrix.arch == 'arm64'
        run: |
          autoupdate
          autoreconf -fi
          ./configure --host=aarch64-linux-gnu CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++

      - name: Configure (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          autoupdate
          autoreconf -fi
          export CPPFLAGS="-I/mingw64/include"
          export LDFLAGS="-L/mingw64/lib"
          ./configure --enable-static --disable-shared --disable-doc

      - name: Build
        if: matrix.os != 'windows-latest'
        run: make -j$(nproc 2>/dev/null || sysctl -n hw.ncpu)
        
      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: make -j$(nproc)

      - name: Package binaries
        if: matrix.os != 'windows-latest'
        run: zip -r ${{ matrix.artifact }}.zip Progs
        
      - name: Package binaries (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: zip -r ${{ matrix.artifact }}.zip Progs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}.zip