name: Build Binaries

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15
            arch: arm64
            artifact: cat-surface-macos-arm64
          - os: macos-15-intel
            arch: x64
            artifact: cat-surface-macos-x86
          - os: ubuntu-22.04
            arch: x64
            artifact: cat-surface-ubuntu-x86_64
          - os: ubuntu-22.04-arm
            arch: arm64
            artifact: cat-surface-ubuntu-arm64
          - os: windows-latest
            arch: x64
            artifact: cat-surface-windows-x86

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      # ---------------- Windows ----------------
      - name: Set up MSYS2
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          install: >
            autoconf automake libtool autoconf-archive make pkgconf gcc
            mingw-w64-x86_64-expat mingw-w64-x86_64-fftw zip

      # ---------------- Ubuntu ----------------
      - name: Install dependencies (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu-22.04')
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake libtool autoconf-archive build-essential \
            pkg-config libfftw3-dev zip
            
      # ---------------- macOS ----------------
      - name: Install dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: brew install autoconf automake libtool autoconf-archive fftw

      # ---------------- Configure ----------------
      - name: Configure (non-Windows)
        if: matrix.os != 'windows-latest'
        run: |
          autoupdate
          autoreconf -fi
          export CPPFLAGS="-I/opt/homebrew/include"
          export LDFLAGS="-L/opt/homebrew/lib"
          ./configure --enable-static --disable-shared --disable-doc

      - name: Configure (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          autoupdate
          autoreconf -fi
          export CPPFLAGS="-I/mingw64/include"
          export LDFLAGS="-L/mingw64/lib"
          ./configure --enable-static --disable-shared --disable-doc

      # ---------------- Build ----------------
      - name: Build
        if: matrix.os != 'windows-latest'
        run: make -j$(nproc 2>/dev/null || sysctl -n hw.ncpu)

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: make -j$(nproc)

      # ---------------- Package ----------------
      - name: Package binaries
        if: matrix.os != 'windows-latest'
        run: zip -r ${{ matrix.artifact }}.zip Progs

      - name: Package binaries (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: zip -r ${{ matrix.artifact }}.zip Progs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}.zip
