name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool build-essential pkg-config libfftw3-dev
      - name: Prepare build
        run: ./autogen.sh
      - name: Configure
        run: ./configure
      - name: Build
        run: make -j$(nproc)
      - name: Run simple tests
        run: |
          make check || true
          ./Progs/CAT_ResampleSurf || true
