name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool autoconf-archive build-essential pkg-config libfftw3-dev zip
      - name: Configure
        run: |
          autoupdate
          autoreconf -fi
          ./configure --enable-static --disable-shared --disable-doc
      - name: Build
        run: make -j$(nproc 2>/dev/null || sysctl -n hw.ncpu)
      - name: Test
        run: make check
      - name: Run simple tests
        run: |
          make check || true
          ./Progs/CAT_ResampleSurf || true